// Day-0 gate (PRD §14). Hits the REAL Cleanverse sandbox — no mocks.
//
//   pnpm --filter @usecordon/cleanverse day0           # resolve config, onboard wallets, get magiclink
//   pnpm --filter @usecordon/cleanverse day0:verify    # re-check A-Pass state after browser enrollment
//
// Writes: <root>/.env, internal/day0-findings.md, internal/wallets.json (gitignored).

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import {
  CleanverseClient,
  CleanverseError,
  selectChain,
  selectToken,
  type ApassData,
  type UserData,
} from "../src/index";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../../..");
const ENV_PATH = resolve(ROOT, ".env");
const FINDINGS_PATH = resolve(ROOT, "internal/day0-findings.md");
const WALLETS_PATH = resolve(ROOT, "internal/wallets.json");

const CHAIN = "monad";
const SYMBOL = "usdc";
const ATOKEN = "ausdc";
const ROLES = ["holding", "operating", "quarantine"] as const;
type Role = (typeof ROLES)[number];

interface WalletRecord {
  role: Role;
  address: string;
  privateKey: string;
}

const ENV_ORDER = [
  "MONAD_RPC_URL",
  "MONAD_CHAIN_ID",
  "MONAD_EXPLORER",
  "DEPLOYER_PRIVATE_KEY",
  "CLEANVERSE_API_BASE",
  "AUSDC_ADDRESS",
  "ACCESS_CORE_ADDRESS",
  "APASS_ADDRESS",
  "HOLDING_WALLET",
  "OPERATING_WALLET",
  "QUARANTINE_WALLET",
] as const;

function readEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(ENV_PATH, "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && m[1] !== undefined) out[m[1]] = m[2] ?? "";
  }
  return out;
}

function writeEnv(vars: Record<string, string>): void {
  const lines = ENV_ORDER.map((k) => `${k}=${vars[k] ?? ""}`);
  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
}

function loadOrCreateWallets(): { wallets: WalletRecord[]; created: boolean } {
  if (existsSync(WALLETS_PATH)) {
    return { wallets: JSON.parse(readFileSync(WALLETS_PATH, "utf8")) as WalletRecord[], created: false };
  }
  const wallets = ROLES.map<WalletRecord>((role) => {
    const privateKey = generatePrivateKey();
    return { role, address: privateKeyToAccount(privateKey).address, privateKey };
  });
  writeFileSync(WALLETS_PATH, JSON.stringify(wallets, null, 2) + "\n");
  return { wallets, created: true };
}

function walletByRole(wallets: WalletRecord[], role: Role): WalletRecord {
  const w = wallets.find((x) => x.role === role);
  if (!w) throw new Error(`wallet for role '${role}' missing in internal/wallets.json`);
  return w;
}

interface ScreenResult {
  role: Role;
  address: string;
  apass: ApassData | null;
  apassError?: string;
  user: UserData | null;
  userError?: string;
}

async function screen(client: CleanverseClient, w: WalletRecord): Promise<ScreenResult> {
  const r: ScreenResult = { role: w.role, address: w.address, apass: null, user: null };
  try {
    r.apass = await client.queryApass(CHAIN, w.address);
  } catch (e) {
    r.apassError = e instanceof CleanverseError ? e.apiMessage : String(e);
  }
  try {
    r.user = await client.queryUser(CHAIN, SYMBOL, w.address);
  } catch (e) {
    r.userError = e instanceof CleanverseError ? e.apiMessage : String(e);
  }
  return r;
}

function findingsMarkdown(args: {
  chainId: number;
  rpc: string;
  explorer: string;
  apass: string;
  ausdc: string;
  ausdcDecimals: number;
  accessCore: string;
  usdc: string;
  wallets: WalletRecord[];
  magiclink: string;
  institutions: string;
  screens: ScreenResult[];
}): string {
  const walletRows = args.wallets
    .map((w) => `| ${w.role} | \`${w.address}\` |`)
    .join("\n");
  const screenRows = args.screens
    .map((s) => {
      const apass = s.apass
        ? `status=${s.apass.status} tier=${s.apass.tier} group=${s.apass.group}`
        : `— (${s.apassError ?? "no data"})`;
      const user = s.user
        ? `status=${s.user.status} blacklist=${s.user.blacklist_reason || "none"}`
        : `— (${s.userError ?? "no data"})`;
      return `| ${s.role} | ${apass} | ${user} |`;
    })
    .join("\n");

  return `# Cordon — Day-0 findings (real Monad sandbox)

> Generated by \`packages/cleanverse/scripts/day0.ts\`. Gitignored. No mocks.

## Monad config (from query_chain_config)

| Field | Value |
|---|---|
| chain_id | \`${args.chainId}\` |
| rpc_url | \`${args.rpc}\` |
| explorer | \`${args.explorer}\` |
| apass_address | \`${args.apass}\` |
| ausdc (A-Token) | \`${args.ausdc}\` (decimals ${args.ausdcDecimals}) |
| access_core | \`${args.accessCore}\` |
| usdc | \`${args.usdc}\` |

## A-Pass test wallets (private keys in internal/wallets.json)

| Role | Address |
|---|---|
${walletRows}

**Enrollment magiclink:** ${args.magiclink}

## Live A-Pass / user state

| Role | query_apass | query_user |
|---|---|---|
${screenRows}

## query_deposit_institutions (monad / usdc)

${args.institutions}

## On-chain confirmations (PRD §14)

1. **Is \`ausdc\` on Monad A-Pass-gated (reverts to non-A-Pass) or advisory?**
   — **UNCONFIRMED.** Cordon is robust either way (it enforces the institution's richer policy regardless). Resolve by attempting an on-chain \`ausdc\` transfer to a non-A-Pass recipient once a funded test wallet exists, or ask in #hackathon-build.
2. **Can a contract address be A-Pass-registered?**
   — **UNCONFIRMED.** Do not invent the A-Pass registry ABI. If yes → vault-contract upgrade path (PRD §4). If no → three-EOA + keeper model stands (current design). Confirm in #hackathon-build.
`;
}

async function main(): Promise<void> {
  const verify = process.argv.includes("--verify");
  const client = new CleanverseClient();

  console.log(`[day0] querying real chain config (${CHAIN})...`);
  const config = await client.queryChainConfig();
  const monad = selectChain(config, CHAIN);
  const ausdc = selectToken(monad, ATOKEN);
  const usdc = selectToken(monad, SYMBOL);

  const { wallets, created } = loadOrCreateWallets();
  if (created) console.log(`[day0] generated 3 fresh A-Pass wallets → internal/wallets.json`);

  const existing = readEnv();
  writeEnv({
    MONAD_RPC_URL: monad.rpc_url,
    MONAD_CHAIN_ID: String(monad.chain_id),
    MONAD_EXPLORER: monad.explorer,
    DEPLOYER_PRIVATE_KEY: existing.DEPLOYER_PRIVATE_KEY ?? "",
    CLEANVERSE_API_BASE: existing.CLEANVERSE_API_BASE || "https://uatapi.cleanverse.com/api/skills",
    AUSDC_ADDRESS: ausdc.token_address,
    ACCESS_CORE_ADDRESS: ausdc.access_core,
    APASS_ADDRESS: monad.apass_address,
    HOLDING_WALLET: walletByRole(wallets, "holding").address,
    OPERATING_WALLET: walletByRole(wallets, "operating").address,
    QUARANTINE_WALLET: walletByRole(wallets, "quarantine").address,
  });
  console.log(`[day0] wrote .env (Monad config + wallet addresses)`);

  const magiclink = (await client.getMagiclink()).register_url;

  // register_data only succeeds once the wallet has an A-Pass (sandbox returns
  // "Please register Apass first!" otherwise), so it runs in the verify pass —
  // after browser enrollment.
  if (verify) {
    for (const w of wallets) {
      const a = await client.queryApassSafe(CHAIN, w.address);
      if (a?.status !== 1) continue;
      try {
        const r = await client.registerData(CHAIN, SYMBOL, w.address);
        console.log(`[day0] register ${w.role.padEnd(10)} ${w.address} → deposit ${r.deposit_address}`);
      } catch (e) {
        const msg = e instanceof CleanverseError ? e.apiMessage : String(e);
        console.log(`[day0] register ${w.role.padEnd(10)} ${w.address} → ${msg}`);
      }
    }
  }

  let institutions = "(query failed)";
  try {
    const di = await client.queryDepositInstitutions(CHAIN, SYMBOL);
    const lines = di.token_whitelist.flatMap((tw) =>
      tw.whitelist.map((w) => `- ${tw.atoken_symbol}: **${w.service_name}** (${w.entity_name}, ${w.category})`),
    );
    institutions = lines.length ? lines.join("\n") : "(empty whitelist)";
  } catch (e) {
    institutions = `(error: ${e instanceof CleanverseError ? e.apiMessage : String(e)})`;
  }

  const screens: ScreenResult[] = [];
  for (const w of wallets) screens.push(await screen(client, w));

  writeFileSync(
    FINDINGS_PATH,
    findingsMarkdown({
      chainId: monad.chain_id,
      rpc: monad.rpc_url,
      explorer: monad.explorer,
      apass: monad.apass_address,
      ausdc: ausdc.token_address,
      ausdcDecimals: ausdc.decimals,
      accessCore: ausdc.access_core,
      usdc: usdc.token_address,
      wallets,
      magiclink,
      institutions,
      screens,
    }),
  );
  console.log(`[day0] wrote internal/day0-findings.md`);

  const active = screens.filter((s) => s.apass?.status === 1).length;
  console.log(`\n[day0] A-Pass active wallets: ${active}/${wallets.length}`);

  if (!verify) {
    console.log(`\n=== ACTION REQUIRED: enroll these 3 wallets at the magiclink ===`);
    console.log(`Magiclink: ${magiclink}`);
    for (const w of wallets) console.log(`  ${w.role.padEnd(10)} ${w.address}`);
    console.log(`Private keys for wallet import: internal/wallets.json`);
    console.log(`After enrolling, run: pnpm --filter @usecordon/cleanverse day0:verify`);
  } else if (active === wallets.length) {
    console.log(`[day0] ✓ all wallets A-Pass active — Day-0 enrollment complete`);
  } else {
    console.log(`[day0] ✗ not all wallets active yet — complete enrollment then re-run :verify`);
    process.exitCode = 1;
  }
}

main().catch((e) => {
  console.error(`[day0] FATAL: ${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
});
